# Generated by Django 3.2.16 on 2022-10-24 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo cliente')),
                ('nombresCliente', models.CharField(max_length=30, verbose_name='Nombre cliente')),
                ('rutCliente', models.CharField(max_length=30, verbose_name='Rut cliente')),
                ('domicilioCliente', models.CharField(max_length=85, verbose_name='Domicilio cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo estado')),
                ('nombreEstado', models.CharField(max_length=30, verbose_name='Nombre estado')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre producto')),
                ('stockProducto', models.IntegerField(verbose_name='Codigo producto')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo proveedor')),
                ('nombresProveedor', models.CharField(max_length=30, verbose_name='Nombre proveedor')),
                ('rutProveedor', models.CharField(max_length=30, verbose_name='Rut proveedor')),
                ('domicilioProveedor', models.CharField(max_length=85, verbose_name='Domicilio proveedor')),
                ('fonoProveedor', models.CharField(max_length=85, verbose_name='Fono proveedor')),
                ('rubroProveedor', models.CharField(max_length=85, verbose_name='Rubro Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('idRecibo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo recibo')),
                ('fechaRecibo', models.DateField(verbose_name='Fecha del Recibo')),
                ('totalRecibo', models.IntegerField(verbose_name='Valor Total')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo cliente')),
                ('nombresServicio', models.CharField(max_length=30, verbose_name='Nombre cliente')),
                ('idEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.estado')),
                ('idProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecibo',
            fields=[
                ('idTipoRecibo', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo tipo recibo')),
                ('nombreTipoRecibo', models.CharField(max_length=30, verbose_name='Nombre tipo recibo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo usuario')),
                ('nombreUsuario', models.CharField(max_length=30, verbose_name='Nombre usuario')),
                ('contraseniaUsuario', models.CharField(max_length=30, verbose_name='Contraseña usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioCliente',
            fields=[
                ('idSolicitud', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Solicitud Servicio')),
                ('fechaSolicitud', models.DateField(verbose_name='Fecha de la Solicitud')),
                ('horaReserva', models.TimeField(verbose_name='Hora de la Reserva')),
                ('idCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cliente')),
                ('idEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.estado')),
                ('idRecibo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.recibo')),
                ('idServicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.servicio')),
            ],
        ),
        migrations.AddField(
            model_name='recibo',
            name='idTipoRecibo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.tiporecibo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='idProveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proveedor'),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo pedido')),
                ('fechaPedido', models.DateField(verbose_name='Fecha del Pedido')),
                ('fechaEntrega', models.DateField(null=True, verbose_name='Fecha de Entrega')),
                ('valorPedido', models.IntegerField(verbose_name='Valor del Pedido')),
                ('idEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.estado')),
                ('idProveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.proveedor')),
                ('idRecibo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.recibo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo empleado')),
                ('nombresEmpleado', models.CharField(max_length=30, verbose_name='Nombre empleado')),
                ('rutEmpleado', models.CharField(max_length=30, verbose_name='Rut empleado')),
                ('idUsuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.usuario'),
        ),
    ]
